# Generated by Django 5.0.6 on 2024-07-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_slug_variacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variacao',
            new_name='Variation',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='produto',
            new_name='product',
        ),
    ]
