# Generated by Django 5.0.6 on 2024-07-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_nome_variation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='promocion_price',
        ),
        migrations.AddField(
            model_name='variation',
            name='promotion_price',
            field=models.FloatField(default=0, verbose_name='Preço Promocional'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque'),
        ),
    ]
