# Generated by Django 5.0.6 on 2024-07-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='product_id',
            field=models.PositiveIntegerField(verbose_name='Produto ID'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='variation_id',
            field=models.PositiveIntegerField(verbose_name='Variacão ID'),
        ),
    ]
