# Generated by Django 4.2.14 on 2024-08-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_orderitems_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade Total'),
            preserve_default=False,
        ),
    ]
